name: Deploy app

on:
  push:
    branches: [ prod ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master
      - uses: actions/setup-node@master

      # Setup virtual env, install dependencies
      - name: install dependencies
        run: npm install

      - name: run build
        run: |
          npm run build
          sh ~/actions-runner/_work/nginx-deploy.sh

